### ISSUE TITLE
Which TF and python version are you using?

### ISSUE THREAD

**Issue by zdnet** [A-bone1/Attention-ocr-Chinese-Version#1]
i got error as below while use own dataset, don't know if due to the reason of version issue:

**(tensorflow-gpu) J:\tensorflow-model\research\attention_ocr\python>python train.py --dataset_name=ctnsizedataset --checkpoint_inception=./attention_ocr_2017_08_09/model.ckpt-399731
Traceback (most recent call last):**
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_flag.py", line 166, in _parse
    return self.parser.parse(argument)
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_argument_parser.py", line 114, in parse
    type(argument)))
TypeError: flag value must be a string, found "<class 'float'>"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 33, in <module>
    common_flags.define()
  File "J:\tensorflow-model\research\attention_ocr\python\common_flags.py", line 77, in define
    'momentum value for the momentum optimizer if used')
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_flag.py", line 107, in __init__
    self._set_default(default)
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_flag.py", line 196, in _set_default
    self.default = self._parse(value)
  File "e:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\absl\flags\_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --momentum=0.9: flag value must be a string, found "<class 'float'>"

(tensorflow-gpu) J:\tensorflow-model\research\attention_ocr\python>

**Comment by zdnet** [comment]
resolved

**Comment by A-bone1** [comment]
I'm so sorry to have seen your question for so long，my python version is 3.5.2 and my tensorflow version is 1.4.0
