### ISSUE TITLE
跑demo_inference_test.py出错

### ISSUE THREAD

**Issue by ruiniao** [A-bone1/Attention-ocr-Chinese-Version#10]
我只简单运行了 python  demo_inference_test.py
出现下面的错误，请指点修正，谢谢！

======================================================================
ERROR: test_moving_variables_properly_loaded_from_a_checkpoint (__main__.DemoInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "demo_inference_test.py", line 26, in test_moving_variables_properly_loaded_from_a_checkpoint
    dataset_name)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/demo_inference.py", line 72, in create_model
    endpoints = model.create_base(images, labels_one_hot=None)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/model.py", line 374, in create_base
    chars_logit = self.sequence_logit_fn(net, labels_one_hot)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/model.py", line 242, in sequence_logit_fn
    layer = layer_class(net, labels_one_hot, self._params, mparams)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/sequence_layers.py", line 381, in __init__
    super(AttentionWithAutoregression, self).__init__(*args, **kwargs)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/sequence_layers.py", line 353, in __init__
    super(Attention, self).__init__(*args, **kwargs)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/sequence_layers.py", line 124, in __init__
    regularizer=regularizer)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 262, in model_variable
    use_resource=use_resource)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 217, in variable
    use_resource=use_resource)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 805, in _get_single_variable
    constraint=constraint)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 213, in __init__
    constraint=constraint)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 779, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/export/wangruifang/projects/attention-ocr-chinese-test/python/sequence_layers.py", line 78, in orthogonal_initializer
    u, _, v = np.linalg.svd(w, full_matrices=False)
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/linalg.py", line 1423, in svd
    _assertNoEmpty2d(a)
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/linalg.py", line 225, in _assertNoEmpty2d
    raise LinAlgError("Arrays cannot be empty")
LinAlgError: Arrays cannot be empty

**Comment by A-bone1** [comment]
@ruiniao 我觉得出错的原因有几个：第一个可能是不支持python2.7的环境；第二个可能是因为我对google给的源代码做了一些修改，导致demo_inference_test.py出错，如果要跑英文的OCR，建议可以到我在readme中提供的Google的github上下载英文版的源代码进行测试

**Comment by ruiniao** [comment]
@A-bone1  谢谢及时回复，用我自己的中间模型已经可以跑出结果了，不过不知为啥loss先从200很快降到60之后又迅速攀升至近1000，这个怎么处理呢？

**Comment by ruiniao** [comment]
@A-bone1  这是在gpu上跑的，batch_size=8才能跑起来，可能需要调整学习率；不知你当时都用过哪些参数对子？

**Comment by A-bone1** [comment]
我当时调的最好的就是现在代码提供的默认参数。

**Comment by A-bone1** [comment]
@ruiniao 我当时调的最好的就是现在代码提供的默认参数。
