### ISSUE TITLE
frozen problem

### ISSUE THREAD

**Issue by nan2088** [A-bone1/Attention-ocr-Chinese-Version#33]
Hi, guys,
I want to freeze the model to a pb file, but got an error:

```
op_kernel.cc:1275 OP_REQUIRES failed at lookup_table_op.cc:675 : Failed precondition: Table not initialized.
Traceback (most recent call last):
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Table not initialized.
         [[Node: import/AttentionOcr_v1/index_to_string_Lookup = LookupTableFindV2[Tin=DT_INT64, Tout=DT_STRING, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/AttentionOcr_v1/index_to_string, import/AttentionOcr_v1/ToInt64/_9, import/AttentionOcr_v1/index_to_string/Const)]]

Caused by op 'import/AttentionOcr_v1/index_to_string_Lookup', defined at:
  File "eval_own.py", line 61, in <module>
    model_test(path_pb, path_img)
  File "eval_own.py", line 31, in model_test
    graph = load_graph(path_pb)
  File "eval_own.py", line 24, in load_graph
    tf.import_graph_def(graph_def)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3289, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3289, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3180, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/zhangsy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Table not initialized.
         [[Node: import/AttentionOcr_v1/index_to_string_Lookup = LookupTableFindV2[Tin=DT_INT64, Tout=DT_STRING, _device="/job:localhost/replica:0/task:0/device:CPU:0"](import/AttentionOcr_v1/index_to_string, import/AttentionOcr_v1/ToInt64/_9, import/AttentionOcr_v1/index_to_string/Const)]]
```

In fact, I modified demo_inference.py as follows:

```
def create_model(batch_size, dataset_name):
  width, height = get_dataset_image_size(dataset_name)
  dataset = common_flags.create_dataset(split_name=FLAGS.split_name)
  tf.initialize_all_tables(name='init_all_tables')
  model = common_flags.create_model(
    num_char_classes=dataset.num_char_classes,
    seq_length=dataset.max_sequence_length,
    num_views=dataset.num_of_views,
    null_code=dataset.null_code,
    charset=dataset.charset)
  #raw_images = tf.placeholder(tf.uint8, shape=[batch_size, height, width, 3], name='input_images') 
  raw_images_o = tf.placeholder(tf.float32, shape=[batch_size, height, width, 3], name='input_images_h')
  
  print("========================================================================")
  print("input : {}".format(raw_images_o))#AttentionOcr_v1/split
  print("========================================================================")

  raw_images = raw_images_o/255.0
  images = tf.map_fn(data_provider.preprocess_image, raw_images,
                     dtype=tf.float32)
  endpoints = model.create_base(images, labels_one_hot=None)
  return raw_images_o, endpoints


def run(checkpoint, batch_size, dataset_name, image_path_pattern):
  images_placeholder, endpoints = create_model(batch_size,
                                               dataset_name)
  images_data = load_images(image_path_pattern, batch_size,
                            dataset_name)
  
  session_creator = monitored_session.ChiefSessionCreator(
    checkpoint_filename_with_path=checkpoint)
  with monitored_session.MonitoredSession(
      session_creator=session_creator) as sess:
    
    
    output_graph=FLAGS.output_graph
    if output_graph != '':
      print("========================================================================")
      print("output : {} {}".format(endpoints.predicted_text, endpoints.predicted_scores))#Tensor("AttentionOcr_v1/ReduceJoin:0", shape=(1,), dtype=string) Tensor("AttentionOcr_v1/Reshape_2:0", shape=(?, 8), dtype=float32)
      print("========================================================================")
      output_graph_def = tf.graph_util.convert_variables_to_constants(sess, tf.get_default_graph().as_graph_def(),
                                                                          [endpoints.predicted_text.name[:-2], endpoints.predicted_scores.name[:-2]])
          # 保存为 pb 文件
      
      with tf.gfile.GFile(output_graph, 'wb') as f:
        f.write(output_graph_def.SerializeToString())
      print('%d ops in the final graph' % (len(output_graph_def.node)))
    #print(images_placeholder)
    predictions = sess.run([endpoints.predicted_text, endpoints.predicted_scores],
                           feed_dict={images_placeholder: images_data})


    #print(predictions)
  return predictions#[x.tolist() for x in predictions]
```

I search the internet but has no idea what can i do. Can you give me some suggestions?

**Comment by A-bone1** [comment]
@ShiyangZhang I am very sorry because I have not tried it.
