### ISSUE TITLE
Predict a random image??

### ISSUE THREAD

**Issue by tuongtranngoc** [A-bone1/Attention-ocr-Chinese-Version#50]
How to predict a single image (random size)?? what file do you run
I run demo_reference.py file, it requere 600x150 include 4 image are combined
Please, thanks

**Comment by A-bone1** [comment]
@NgTuong You can predict a single image by changing the number of view in the configuration file /python/datasets/fsns.py to 1.

**Comment by tuongtranngoc** [comment]
HI , @A-bone1 thanks,
i did but miss
Traceback (most recent call last):
  File "demo_inference.py", line 98, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "demo_inference.py", line 91, in main
    FLAGS.image_path_pattern)
  File "demo_inference.py", line 77, in run
    dataset_name)
  File "demo_inference.py", line 50, in load_images
    path = file_pattern % i
TypeError: not all arguments converted during string formatting

**Comment by MGpraveenbond** [comment]
I am also facing the same problem when i run the demo_inference.py . I have set the number of view as 1 in fsns.py .any body got the solution for this.
