### ISSUE TITLE
how to use train.py??

### ISSUE THREAD

**Issue by 21toanyone-pro** [A-bone1/Attention-ocr-Chinese-Version#52]
I use default tfrecode in your git. 

and I execution train.py.

but error 

 File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_flag.py", line 181, in _parse
    return self.parser.parse(argument)
  File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_argument_parser.py", line 114, in parse
    type(argument)))
TypeError: flag value must be a string, found "<class 'float'>"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Lim\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\Lim\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 357, in main
    run()
  File "c:\Users\Lim\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Lim\Desktop\ocr\python\train.py", line 35, in <module>
    common_flags.define()
  File "c:\Users\Lim\Desktop\ocr\python\common_flags.py", line 77, in define
    'momentum value for the momentum optimizer if used')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_flag.py", line 110, in __init__
    self._set_default(default)
  File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_flag.py", line 211, in _set_default
    self.default = self._parse(value)
  File "C:\Users\Lim\AppData\Roaming\Python\Python37\site-packages\absl\flags\_flag.py", line 184, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --momentum=0.9: flag value must be a string, found "<class 'float'>"

I use Windows10 and Ubuntu16.04

but Both errors

I use tensorflow 1.13 and CUDA 8.0, python 3.7 

Perhaps Is there anything I need to do before running train.py?

**Comment by A-bone1** [comment]
you may solved this problem by changing one line in the common_flags.py:
from
flags.DEFINE_string('momentum', 0.9,
'momentum value for the momentum optimizer if used')
to
flags.DEFINE_float('momentum', 0.9,
'momentum value for the momentum optimizer if used')

**Comment by Duskprime** [comment]
I solved the problem.

but next error

INFO 2019-03-17 19:50:48.000931: train.py: 160 Create a new training directory /home/ucmed/opt/python/models-master/research/attention_ocr/python/logs
Traceback (most recent call last):
  File "/home/lim/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/home/lim/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/lib/python/ptvsd/__main__.py", line 357, in main
    run()
  File "/home/lim/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/lib/python/ptvsd/__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/lim/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/lim/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/lim/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lim/ocr/python/train.py", line 211, in <module>
    app.run()
  File "/home/lim/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/lim/ocr/python/train.py", line 180, in main
    prepare_training_dir()
  File "/home/lim/ocr/python/train.py", line 161, in prepare_training_dir
    tf.gfile.MakeDirs(FLAGS.train_log_dir)
  File "/home/lim/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/home/lim/anaconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "/home/lim/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /home/ucmed; Permission denied

What is the problem?
